# Generated by Django 2.2.1 on 2019-05-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='desc',
        ),
        migrations.AddField(
            model_name='goodssku',
            name='origin_place',
            field=models.CharField(default='', max_length=50, verbose_name='商品产地'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodssku',
            name='remarks',
            field=models.CharField(default='', max_length=256, verbose_name='商品备注'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodssku',
            name='specification',
            field=models.CharField(default='', max_length=256, verbose_name='商品规格'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名称'),
        ),
    ]
