# Generated by Django 2.2.1 on 2019-05-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190515_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssku',
            name='origin_place',
        ),
        migrations.RemoveField(
            model_name='goodssku',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='goodssku',
            name='specification',
        ),
        migrations.AddField(
            model_name='goodssku',
            name='desc',
            field=models.CharField(default='', max_length=256, verbose_name='商品简介'),
            preserve_default=False,
        ),
    ]
