# Generated by Django 2.2.1 on 2019-05-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190520_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='spu_banner01',
            field=models.ImageField(default='', upload_to='goods', verbose_name='商品Banner图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='spu_banner02',
            field=models.ImageField(default='', upload_to='goods', verbose_name='商品Banner图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='spu_banner03',
            field=models.ImageField(default='', upload_to='goods', verbose_name='商品Banner图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='spu_top_banner',
            field=models.ImageField(default='', upload_to='goods', verbose_name='商品TopBanner图片'),
        ),
    ]
