# Generated by Django 2.2.1 on 2019-05-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartInfo',
        ),
    ]
